INSERT INTO equipamientos (id_equipamiento, nombre_equipamiento, tipo, nivel_requerido, bono_ataque, bono_defensa) VALUES
(1, 'Espada Cortante', 'arma', 1, 5, 0),
(2, 'Escudo de Hierro', 'escudo', 1, 0, 3),
(3, 'Armadura de Cuero', 'armadura', 2, 0, 4),
(4, 'Hacha de Batalla', 'arma', 3, 7, 0),
(5, 'Capa de Protección', 'accesorio', 2, 0, 5),
(6, 'Báculo de Hechicería', 'arma', 5, 6, 0),
(7, 'Guantes de Batalla', 'accesorio', 4, 3, 2),
(8, 'Botas de Velocidad', 'accesorio', 3, 2, 1),
(9, 'Espada Larga', 'arma', 4, 8, 0),
(10, 'Escudo de Cristal', 'escudo', 5, 0, 6),
(11, 'Armadura de Placas', 'armadura', 6, 0, 10),
(12, 'Hacha de Dos Manos', 'arma', 7, 10, 0),
(13, 'Capa de Sigilo', 'accesorio', 5, 0, 7),
(14, 'Espada de Fuego', 'arma', 8, 9, 0),
(15, 'Anillo de Poder', 'accesorio', 6, 4, 0),
(16, 'Guantes de Agilidad', 'accesorio', 4, 2, 1),
(17, 'Báculo de Fuego', 'arma', 9, 12, 0),
(18, 'Botas de la Agilidad', 'accesorio', 3, 1, 2),
(19, 'Armadura de Acero', 'armadura', 5, 0, 8),
(20, 'Espada de Hielo', 'arma', 9, 11, 0),
(21, 'Escudo de la Fe', 'escudo', 7, 0, 5),
(22, 'Capa de la Noche', 'accesorio', 6, 0, 8),
(23, 'Espada de Luz', 'arma', 10, 13, 0),
(24, 'Hacha de Guerrero', 'arma', 8, 9, 0),
(25, 'Guantes de Hechicero', 'accesorio', 7, 2, 0),
(26, 'Báculo del Viento', 'arma', 10, 14, 0),
(27, 'Armadura del Dragón', 'armadura', 10, 0, 12),
(28, 'Anillo de Invulnerabilidad', 'accesorio', 9, 0, 10),
(29, 'Escudo del Valor', 'escudo', 8, 0, 7),
(30, 'Capa de Resistencia', 'accesorio', 7, 0, 6);
