INSERT INTO recompensas (id_recompensa, tipo_recompensa, descripcion_recompensa) VALUES
(1, 'Oro', '100 piezas de oro.'),
(2, 'Espada de Acero', 'Espada larga de acero, aumenta el ataque en 5 puntos.'),
(3, 'Poción de Curación', 'Poción que restaura 50 puntos de vida.'),
(4, 'Escudo de Madera', 'Escudo de madera resistente, aumenta la defensa en 3 puntos.'),
(5, 'Anillo Protector', 'Anillo que otorga +2 a la defensa.'),
(6, 'Oro Brillante', '200 piezas de oro brillante, muy valoradas.'),
(7, 'Armadura de Cuero', 'Armadura que aumenta la defensa en 4 puntos.'),
(8, 'Poción de Mana', 'Poción que restaura 30 puntos de mana.'),
(9, 'Hacha de Guerra', 'Hacha que aumenta el ataque en 7 puntos.'),
(10, 'Oro Antiguo', '150 piezas de oro antiguo, apreciadas por coleccionistas.'),
(11, 'Capa de Invisibilidad', 'Capa que otorga +5 a la evasión.'),
(12, 'Báculo Mágico', 'Báculo que aumenta el poder mágico en 6 puntos.'),
(13, 'Oro Sagrado', '250 piezas de oro sagrado, usado en rituales.'),
(14, 'Guantes de Fuerza', 'Guantes que otorgan +3 al ataque.'),
(15, 'Poción de Resistencia', 'Poción que aumenta la salud máxima en 20 puntos temporalmente.'),
(16, 'Oro de los Reyes', '300 piezas de oro de los reyes, muy raras.'),
(17, 'Espada Encantada', 'Espada que aumenta el ataque en 10 puntos y tiene un 10% de probabilidad de infligir daño adicional.'),
(18, 'Escudo Mágico', 'Escudo que otorga un bono de defensa adicional contra ataques mágicos.'),
(19, 'Oro de la Fortuna', '500 piezas de oro de la fortuna, trae buena suerte.'),
(20, 'Tomo de Hechizos', 'Tomo que permite aprender un nuevo hechizo.'),
(21, 'Poción de Velocidad', 'Poción que aumenta la agilidad temporalmente.'),
(22, 'Cofre de Tesoros', 'Cofre que contiene varios objetos valiosos.'),
(23, 'Anillo de Magia', 'Anillo que otorga +5 a la inteligencia.'),
(24, 'Oro Valioso', '400 piezas de oro valioso, utilizado en comercio.'),
(25, 'Armadura de Acero', 'Armadura que aumenta la defensa en 8 puntos.'),
(26, 'Poción de Invulnerabilidad', 'Poción que otorga invulnerabilidad temporal durante 30 segundos.'),
(27, 'Oro Legendario', '600 piezas de oro legendario, considerado sagrado.'),
(28, 'Espada de Dragón', 'Espada forjada con el metal de un dragón, otorga +15 de ataque.'),
(29, 'Cruz de Protección', 'Cruz sagrada que otorga +10 a la defensa contra no-muertos.'),
(30, 'Máscara del Mago', 'Máscara que aumenta el poder mágico en 8 puntos y oculta la identidad.');
